-- Role: "adminPeople"
-- DROP ROLE IF EXISTS "adminPeople";

CREATE ROLE "adminPeople" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:NClZTx18RoYlF8tHEcgK/A==$WvHG/dMtl6ALKqjUAZE0xbOyHztdHevruH0sB0wNXGw=:xShsINnJF/KNZ45jXJo78/6XHd58xNANxQ3MxYRthYo=';